name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    # Suggest using stable branch, tag or sha.
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@main
    permissions:
      contents: write
    with:
      skip-node-setup: true
      skip-appstore-release: true
